version: "3"

services:
  movie_review_db:
    container_name: movie_review_db
    build:
      context: mysql
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - CHARACTER_SET_SERVER=utf8%
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - movie_review_db:/var/lib/${DB_NAME}
    ports:
      - "${DB_PORT}:3306"

  main-server:
    container_name: main-server
    build:
      context: movieReview
      dockerfile: Dockerfile
    env_file:
      - .env
    image: main-server
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - movie_review_db

volumes:
  movie_review_db: