// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// ReviewDelivery is an autogenerated mock type for the ReviewDelivery type
type ReviewDelivery struct {
	mock.Mock
}

// Create provides a mock function with given fields: c
func (_m *ReviewDelivery) Create(c *gin.Context) {
	_m.Called(c)
}

// FindAllByMovieId provides a mock function with given fields: c
func (_m *ReviewDelivery) FindAllByMovieId(c *gin.Context) {
	_m.Called(c)
}

// NewReviewDelivery creates a new instance of ReviewDelivery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReviewDelivery(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReviewDelivery {
	mock := &ReviewDelivery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
