// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	domain "movieReview/review/domain"

	mock "github.com/stretchr/testify/mock"
)

// ReviewUseCase is an autogenerated mock type for the ReviewUseCase type
type ReviewUseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: req
func (_m *ReviewUseCase) Create(req domain.CreateRequest) (domain.Response, error) {
	ret := _m.Called(req)

	var r0 domain.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.CreateRequest) (domain.Response, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(domain.CreateRequest) domain.Response); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(domain.Response)
	}

	if rf, ok := ret.Get(1).(func(domain.CreateRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByMovieId provides a mock function with given fields: params
func (_m *ReviewUseCase) FindAllByMovieId(params domain.FindAllParams) ([]domain.Response, error) {
	ret := _m.Called(params)

	var r0 []domain.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.FindAllParams) ([]domain.Response, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(domain.FindAllParams) []domain.Response); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.FindAllParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReviewUseCase creates a new instance of ReviewUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReviewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReviewUseCase {
	mock := &ReviewUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
