// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	domain "movieReview/movie/domain"

	mock "github.com/stretchr/testify/mock"
)

// MovieRepository is an autogenerated mock type for the MovieRepository type
type MovieRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: movie
func (_m *MovieRepository) Create(movie domain.Movie) (domain.Movie, error) {
	ret := _m.Called(movie)

	var r0 domain.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.Movie) (domain.Movie, error)); ok {
		return rf(movie)
	}
	if rf, ok := ret.Get(0).(func(domain.Movie) domain.Movie); ok {
		r0 = rf(movie)
	} else {
		r0 = ret.Get(0).(domain.Movie)
	}

	if rf, ok := ret.Get(1).(func(domain.Movie) error); ok {
		r1 = rf(movie)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *MovieRepository) Delete(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: params
func (_m *MovieRepository) FindAll(params domain.FindAllParams) ([]domain.Response, error) {
	ret := _m.Called(params)

	var r0 []domain.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.FindAllParams) ([]domain.Response, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(domain.FindAllParams) []domain.Response); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.FindAllParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllByScore provides a mock function with given fields: params
func (_m *MovieRepository) FindAllByScore(params domain.PaginationParams) ([]domain.ScoreRankResponse, error) {
	ret := _m.Called(params)

	var r0 []domain.ScoreRankResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.PaginationParams) ([]domain.ScoreRankResponse, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(domain.PaginationParams) []domain.ScoreRankResponse); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ScoreRankResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.PaginationParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindById provides a mock function with given fields: id
func (_m *MovieRepository) FindById(id string) (domain.Movie, error) {
	ret := _m.Called(id)

	var r0 domain.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (domain.Movie, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) domain.Movie); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Movie)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, movie
func (_m *MovieRepository) Update(id string, movie domain.CreateRequest) (domain.Movie, error) {
	ret := _m.Called(id, movie)

	var r0 domain.Movie
	var r1 error
	if rf, ok := ret.Get(0).(func(string, domain.CreateRequest) (domain.Movie, error)); ok {
		return rf(id, movie)
	}
	if rf, ok := ret.Get(0).(func(string, domain.CreateRequest) domain.Movie); ok {
		r0 = rf(id, movie)
	} else {
		r0 = ret.Get(0).(domain.Movie)
	}

	if rf, ok := ret.Get(1).(func(string, domain.CreateRequest) error); ok {
		r1 = rf(id, movie)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMovieRepository creates a new instance of MovieRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMovieRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MovieRepository {
	mock := &MovieRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
