// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// MovieDelivery is an autogenerated mock type for the MovieDelivery type
type MovieDelivery struct {
	mock.Mock
}

// Create provides a mock function with given fields: c
func (_m *MovieDelivery) Create(c *gin.Context) {
	_m.Called(c)
}

// Delete provides a mock function with given fields: c
func (_m *MovieDelivery) Delete(c *gin.Context) {
	_m.Called(c)
}

// FindAll provides a mock function with given fields: c
func (_m *MovieDelivery) FindAll(c *gin.Context) {
	_m.Called(c)
}

// FindAllByScore provides a mock function with given fields: c
func (_m *MovieDelivery) FindAllByScore(c *gin.Context) {
	_m.Called(c)
}

// FindById provides a mock function with given fields: c
func (_m *MovieDelivery) FindById(c *gin.Context) {
	_m.Called(c)
}

// Update provides a mock function with given fields: c
func (_m *MovieDelivery) Update(c *gin.Context) {
	_m.Called(c)
}

// NewMovieDelivery creates a new instance of MovieDelivery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMovieDelivery(t interface {
	mock.TestingT
	Cleanup(func())
}) *MovieDelivery {
	mock := &MovieDelivery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
